export const languages = [
    "English",
    "Hindi",
    "French",
    "Spanish",
    "German",
    "Italian",
    "Portuguese",
    "Russian",
    "Chinese (Simplified)",
    "Japanese",
    "Korean",
    "Arabic",
    "Turkish",
    "Dutch",
    "Bengali",
    "Tamil",
    "Telugu",
    "Marathi",
    "Urdu",
    "Punjabi"
];